# Generated by Django 4.1 on 2023-05-22 19:48

from django.db import migrations, models
import pembuatan_pertandingan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertandingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField()),
                ('stadium', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pertandingan', models.DateTimeField(validators=[pembuatan_pertandingan.models.validate_jadwal_tim_wasit])),
            ],
        ),
        migrations.CreateModel(
            name='Wasit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pertandingan', models.DateTimeField(validators=[pembuatan_pertandingan.models.validate_jadwal_tim_wasit])),
            ],
        ),
    ]
