# Generated by Django 4.1 on 2023-05-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertandingan',
            fields=[
                ('id_pertandingan', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('stadium', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id_stadium', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
                ('kapasitas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tim', models.CharField(max_length=100, unique=True)),
                ('universitas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wasit',
            fields=[
                ('id_wasit', models.AutoField(primary_key=True, serialize=False)),
                ('lisensi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WasitBertugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi_wasit', models.CharField(max_length=100)),
                ('id_pertandingan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembuatan_pertandingan.pertandingan')),
                ('wasit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembuatan_pertandingan.wasit')),
            ],
        ),
        migrations.CreateModel(
            name='TimPertandingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.IntegerField()),
                ('id_pertandingan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembuatan_pertandingan.pertandingan')),
                ('id_tim_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembuatan_pertandingan.tim')),
            ],
        ),
    ]
